apiVersion: v1
clusters:
    - cluster:
          certificate-authority-data: BASE64ENCODED_CERTIFICATE
          server: https://your-kubernetes-cluster-server.com
      name: my-cluster
contexts:
    - context:
          cluster: my-cluster
          user: my-user
      name: my-context
current-context: my-context
kind: Config
preferences: {}
users:
    - name: my-user
      user:
          client-certificate-data: BASE64ENCODED_CLIENT_CERTIFICATE
          client-key-data: BASE64ENCODED_CLIENT_KEY
