apiVersion: v1
kind: Service
metadata:
    name: secureweather
spec:
    selector:
        app: secureweather
    ports:
        -   protocol: TCP
            port: 80
            targetPort: 8080
    type: LoadBalancer

